---
- name: Installing java
  hosts: webserver
  sudo: yes
  tasks: 
    - apt_repository: repo='ppa:webupd8team/java'
#     - name: Autoaccept license for Java7
#      debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Autoaccept license for Java8
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Java
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default
